force-app/main/default/objects/ApplicationLog__c/ApplicationLog__c.object-meta.xml
<CustomObject>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG-{0000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationLog__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ApplicationLogTriggerHandler.cls
public with sharing class ApplicationLogTriggerHandler extends TriggerBase{
    public static final String TRIG_SETTING = 'Application Log';
    public ApplicationLogTriggerHandler() {
        super(TRIG_SETTING);
    }

    public override void afterInsert(Map<Id, SObject> triggerNew) {
        sendImmediateLogAlert((List<ApplicationLog__c>) triggerNew.values());
	}

    public static void sendImmediateLogAlert(List<ApplicationLog__c> appLogList){
        List<Id> immediateAppLogIdList = new List<Id>();
        for(ApplicationLog__c appLog :appLogList){
            if(ApplicationLogUtility.IMMEDIATE_PRIORITY_LIST.contains(appLog.Priority__c )){
                immediateAppLogIdList.add(appLog.Id);
            }
        }

        ApplicationLogUtility.sendLogAlert(immediateAppLogIdList);
    }
}