force-app/main/default/objects/ApplicationLog__c/ApplicationLog__c.object-meta.xml
<CustomObject>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG-{0000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationLog__c/fields/ApexClassName__c.field-meta.xml
<CustomField>
    <fullName>ApexClassName__c</fullName>
    <label>Apex Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DeleteTrim.cls
public with sharing class DeleteTrim implements Database.Batchable<SObject>{
    public Database.QueryLocator start(Database.BatchableContext bc){
		//String query  = 'SELECT Id FROM Vehicle_Model_Trim__c';
        String className = 'VehicleResource';
        String query = 'SELECT Id FROM ApplicationLog__c WHERE ApexClassName__c = :className';

		return Database.getQueryLocator(query);
    }
/*
    public void execute(Database.BatchableContext bc, List<Vehicle_Model_Trim__c> trimList){
        delete trimList;
    }
*/
    public void execute(Database.BatchableContext bc, List<ApplicationLog__c> trimList){
        delete trimList;
    }

    public void finish(Database.BatchableContext bc){
        system.debug('finished');
    }
}