force-app/main/default/objects/ApplicationLog__c/ApplicationLog__c.object-meta.xml
<CustomObject>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG-{0000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationLog__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <label>Error Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ApplicationLog__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DataFrame_Test.cls
@isTest
public with sharing class DataFrame_Test {
    @isTest
    static void shortHeaders(){
        List<String> rowList = new List<String>();
        rowList.add('H1,H2,H3\n');
        rowList.add('v1,v2,v3,v4');
        DataFrame invalidDF = new DataFrame(',',rowList);
        List<ApplicationLog__c> appLogs = [
            SELECT Id
            FROM ApplicationLog__c
            WHERE Priority__c = :ApplicationLogUtility.PRIORITY_LOW
                AND ErrorMessage__c LIKE '%row NOT added to dataframe%'
        ];
        System.assertEquals(1,appLogs.size());
    }

    @isTest
    static void longHeaders(){
        List<String> rowList = new List<String>();
        rowList.add('H1,H2,H3\n');
        rowList.add('v1,v2');
        DataFrame invalidDF = new DataFrame(',',rowList);
        System.assertEquals(null,invalidDF.get(0).get('H3'));
        System.assertEquals(null,invalidDF.get(13));
    }

	@isTest
	static void coverage() {
		List<String> rowList = new List<String>();
        rowList.add('H1,H2,H3\n');
        rowList.add('v1,v2');
        DataFrame invalidDF = new DataFrame(',',rowList);
        invalidDF.getLength();
		invalidDF.debug();
		string html = invalidDF.html;
	}
}